extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  comments:
    min-spaces-from-content: 2

  comments-indentation: disable

  document-start: disable

  truthy:
    allowed-values: ['true', 'false']
    check-keys: false

  brackets:
    max-spaces-inside: 1

  braces:
    max-spaces-inside: 1

  colons:
    max-spaces-after: 1

  commas:
    max-spaces-after: 1

  empty-lines:
    max: 2

  hyphens:
    max-spaces-after: 1

  key-duplicates: enable

  quoted-strings:
    quote-type: single
    required: only-when-needed

ignore: |
  .github/workflows/
  templates/examples/
  node_modules/
  .venv/
  venv/
  htmlcov/
  dist/
  build/
  *.egg-info/
