global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # MCP Standards Server metrics
  - job_name: "mcp-standards-server"
    static_configs:
      - targets: ["mcp-server:8080"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis metrics (if redis_exporter is added)
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 5s