name: Check Package Build

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'setup.py'
      - 'setup.cfg'
      - 'MANIFEST.in'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'setup.py'
      - 'setup.cfg'
      - 'MANIFEST.in'

jobs:
  build-check:
    name: Check package build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      
      - name: Build package
        run: python -m build
      
      - name: Check package with twine
        run: twine check dist/*
      
      - name: Test install from wheel
        run: |
          python -m venv test-env
          source test-env/bin/activate
          pip install dist/*.whl
          mcp-standards --version
          deactivate
          rm -rf test-env
      
      - name: Test install from sdist
        run: |
          python -m venv test-env-sdist
          source test-env-sdist/bin/activate
          pip install dist/*.tar.gz
          mcp-standards --version
          deactivate
          rm -rf test-env-sdist