name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * MON'  # Weekly on Monday
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
      
      - name: Update Python dependencies
        run: |
          # Create requirements.in if it doesn't exist
          if [ ! -f requirements.in ]; then
            cp requirements.txt requirements.in
          fi
          
          # Update dependencies
          pip-compile --upgrade --resolver=backtracking requirements.in
          
          # Check if there are changes
          if git diff --quiet requirements.txt; then
            echo "No dependency updates available"
            exit 0
          fi
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Update Python dependencies'
          title: 'chore: Update Python dependencies'
          body: |
            ## Automated Dependency Updates
            
            This PR updates the Python dependencies to their latest compatible versions.
            
            ### Changes
            - Updated `requirements.txt` with latest dependency versions
            
            ### Checklist
            - [ ] All tests pass
            - [ ] No breaking changes identified
            - [ ] Security vulnerabilities addressed
            
            ---
            *This PR was automatically generated by the dependency update workflow.*
          branch: deps/python-updates
          delete-branch: true
          labels: |
            dependencies
            automated