version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: web/deployment/Dockerfile.backend
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./app.db}
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ../
      dockerfile: web/deployment/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data: